import json
import math
import os
import sys

def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_config.py <input_json> <output_hpp>")
        return

    json_path = sys.argv[1]
    hpp_path = sys.argv[2]

    # 1. Read the JSON file
    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Notice: {json_path} not found. Using default values.")
        data = {}

    # 2. Extract values (Default to 4096 if missing)
    max_entities = data.get("Max-Entities", 4096)
    max_components = data.get("Max-Components", 32)
    max_render_commands = data.get("Max-Render-Commands", 8192)

    max_textures = data.get("Max-Textures", 128);
    max_sounds = data.get("Max-Sounds", 128);
    max_musics = data.get("Max-Musics", 128);

    if max_entities > (1 << 64) - 2:
        max_entities = (1 << 64) - 2

    if max_render_commands > 8192:
        max_render_commands = 8192
    
    # 3. Calculate dependent variables
    entity_index_bits = int(math.log2(max_entities))
    entity_generation_bits = 64 - entity_index_bits
    entity_index_mask = (1 << entity_index_bits) - 1
    entity_generation_mask = ((1 << entity_generation_bits) - 1) << entity_index_bits

    max_entity_generation = (1 << entity_generation_bits) - 1

    # 4. Write the C++ Header
    cpp_code = f"""// AUTO-GENERATED BY PYTHON. DO NOT EDIT.
#pragma once
#include <cstdint>

namespace vortex::config 
{{
    // Independent (From JSON)
    constexpr uint64_t MAX_ENTITIES = {max_entities};
    constexpr size_t MAX_COMPONENTS = {max_components};
    constexpr size_t MAX_RENDER_COMMANDS = {max_render_commands};
    constexpr size_t MAX_TEXTURES = {max_textures};
    constexpr size_t MAX_SOUNDS = {max_sounds};
    constexpr size_t MAX_MUSICS = {max_musics};
    
    // Dependent (Calculated by Python)
    constexpr uint64_t ENTITY_INDEX_BITS = {entity_index_bits};
    constexpr uint64_t ENTITY_GENERATION_BITS = {entity_generation_bits};
    constexpr uint64_t ENTITY_INDEX_MASK = 0x{entity_index_mask:X};
    constexpr uint64_t ENTITY_GENERATION_MASK = 0x{entity_generation_mask:X};

    constexpr uint64_t MAX_ENTITY_GENERATION = 0x{max_entity_generation:X};
}}

#define VX_NEW(Type, ...) new Type(__VA_ARGS__)
#define VX_DELETE(ptr) delete ptr

#define VX_NEW_S(Type, size) new Type[size] // Sequence new (For Arrays)
#define VX_DELETE_S(ptr) delete[] ptr // Sequence delete (For Arrays)

// Defining a universal function signature type to get template function signatures
#if defined(_MSC_VER)
        #define VX_FUNC_SIG __FUNCSIG__
    #elif defined(__GNUC__) || defined(__clang__)
        #define VX_FUNC_SIG __PRETTY_FUNCTION__
    #else
        #define VX_FUNC_SIG __func__
#endif
"""

    os.makedirs(os.path.dirname(hpp_path), exist_ok=True)
    with open(hpp_path, 'w') as f:
        f.write(cpp_code)
    
    print(f"Successfully generated {os.path.basename(hpp_path)}")

if __name__ == "__main__":
    main()
