// AUTO-GENERATED BY PYTHON. DO NOT EDIT.
#pragma once
#include <cstdint>

namespace vortex::config
{
    // Independent (From JSON)
    constexpr uint64_t MAX_ENTITIES = 4096;
    constexpr size_t MAX_COMPONENTS = 32;
    constexpr size_t MAX_RENDER_COMMANDS = 8192;
    constexpr size_t MAX_TEXTURES = 128;
    constexpr size_t MAX_SOUNDS = 128;
    constexpr size_t MAX_MUSICS = 128;
    constexpr int INITIAL_WINDOW_WIDTH = 1280;
    constexpr int INITIAL_WINDOW_HEIGHT = 720;
    constexpr int INITIAL_RESOLUTION_WIDTH = 1920;
    constexpr int INITIAL_RESOLUTION_HEIGHT = 1080;

    // Dependent (Calculated by Python)
    constexpr uint64_t ENTITY_INDEX_BITS = 12;
    constexpr uint64_t ENTITY_GENERATION_BITS = 52;
    constexpr uint64_t ENTITY_INDEX_MASK = 0xFFF;
    constexpr uint64_t ENTITY_GENERATION_MASK = 0xFFFFFFFFFFFFF000;

    constexpr uint64_t MAX_ENTITY_GENERATION = 0xFFFFFFFFFFFFF;
}

#define VX_NEW(Type, ...) new Type(__VA_ARGS__)
#define VX_DELETE(ptr) delete ptr

#define VX_NEW_S(Type, size) new Type[size] // Sequence new (For Arrays)
#define VX_DELETE_S(ptr) delete[] ptr       // Sequence delete (For Arrays)

// Defining a universal function signature type to get template function signatures
#if defined(_MSC_VER)
#define VX_FUNC_SIG __FUNCSIG__
#elif defined(__GNUC__) || defined(__clang__)
#define VX_FUNC_SIG __PRETTY_FUNCTION__
#else
#define VX_FUNC_SIG __func__
#endif